# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/falcon/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/falcon/proprietary/bin/akmd8963:system/bin/akmd8963 \
    vendor/motorola/falcon/proprietary/etc/Bluetooth_cal.acdb:system/etc/Bluetooth_cal.acdb \
    vendor/motorola/falcon/proprietary/etc/firmware/aps-Falc-01300000-0130-falcon.tdat:system/etc/firmware/aps-Falc-01300000-0130-falcon.tdat \
    vendor/motorola/falcon/proprietary/etc/firmware/synaptics-s2316-13091704-175833-falcon.tdat:system/etc/firmware/synaptics-s2316-13091704-175833-falcon.tdat \
    vendor/motorola/falcon/proprietary/etc/General_cal.acdb:system/etc/General_cal.acdb \
    vendor/motorola/falcon/proprietary/etc/Global_cal.acdb:system/etc/Global_cal.acdb \
    vendor/motorola/falcon/proprietary/etc/Handset_cal.acdb:system/etc/Handset_cal.acdb \
    vendor/motorola/falcon/proprietary/etc/Hdmi_cal.acdb:system/etc/Hdmi_cal.acdb \
    vendor/motorola/falcon/proprietary/etc/Headset_cal.acdb:system/etc/Headset_cal.acdb \
    vendor/motorola/falcon/proprietary/etc/Speaker_cal.acdb:system/etc/Speaker_cal.acdb \
    vendor/motorola/falcon/proprietary/lib/hw/camera.vendor.msm8226.so:system/lib/hw/camera.vendor.msm8226.so \
    vendor/motorola/falcon/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/motorola/falcon/proprietary/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
    vendor/motorola/falcon/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/motorola/falcon/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/motorola/falcon/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/motorola/falcon/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/motorola/falcon/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/motorola/falcon/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/motorola/falcon/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/motorola/falcon/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/motorola/falcon/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/motorola/falcon/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/motorola/falcon/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/motorola/falcon/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/motorola/falcon/proprietary/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so

PRODUCT_COPY_FILES += \
    vendor/motorola/falcon/proprietary/vendor/firmware/mba.b00:system/vendor/firmware/mba.b00 \
    vendor/motorola/falcon/proprietary/vendor/firmware/mba.mdt:system/vendor/firmware/mba.mdt \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.b00:system/vendor/firmware/modem.b00 \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.b01:system/vendor/firmware/modem.b01 \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.b02:system/vendor/firmware/modem.b02 \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.b03:system/vendor/firmware/modem.b03 \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.b04:system/vendor/firmware/modem.b04 \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.b05:system/vendor/firmware/modem.b05 \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.b08:system/vendor/firmware/modem.b08 \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.b11:system/vendor/firmware/modem.b11 \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.b13:system/vendor/firmware/modem.b13 \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.b15:system/vendor/firmware/modem.b15 \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.b16:system/vendor/firmware/modem.b16 \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.b17:system/vendor/firmware/modem.b17 \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.b18:system/vendor/firmware/modem.b18 \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.b19:system/vendor/firmware/modem.b19 \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.b20:system/vendor/firmware/modem.b20 \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.b21:system/vendor/firmware/modem.b21 \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.b22:system/vendor/firmware/modem.b22 \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.b25:system/vendor/firmware/modem.b25 \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.b26:system/vendor/firmware/modem.b26 \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.b27:system/vendor/firmware/modem.b27 \
    vendor/motorola/falcon/proprietary/vendor/firmware/modem.mdt:system/vendor/firmware/modem.mdt \
    vendor/motorola/falcon/proprietary/vendor/firmware/wcnss.b00:system/vendor/firmware/wcnss.b00 \
    vendor/motorola/falcon/proprietary/vendor/firmware/wcnss.b01:system/vendor/firmware/wcnss.b01 \
    vendor/motorola/falcon/proprietary/vendor/firmware/wcnss.b02:system/vendor/firmware/wcnss.b02 \
    vendor/motorola/falcon/proprietary/vendor/firmware/wcnss.b04:system/vendor/firmware/wcnss.b04 \
    vendor/motorola/falcon/proprietary/vendor/firmware/wcnss.b06:system/vendor/firmware/wcnss.b06 \
    vendor/motorola/falcon/proprietary/vendor/firmware/wcnss.b07:system/vendor/firmware/wcnss.b07 \
    vendor/motorola/falcon/proprietary/vendor/firmware/wcnss.b08:system/vendor/firmware/wcnss.b08 \
    vendor/motorola/falcon/proprietary/vendor/firmware/wcnss.b09:system/vendor/firmware/wcnss.b09 \
    vendor/motorola/falcon/proprietary/vendor/firmware/wcnss.mdt:system/vendor/firmware/wcnss.mdt
